#!/bin/sh
set -eu

cat > /app/.env <<EOF
APP_NAME=${APP_NAME:-灵果短剧}
APP_ENV=${APP_ENV:-production}
APP_KEY=${APP_KEY:-change-me-in-production}
APP_DEBUG=${APP_DEBUG:-false}
APP_URL=${APP_URL:-http://localhost:8080}
APP_PORT=${APP_PORT:-8080}
TIMEZONE=${TIMEZONE:-Asia/Shanghai}

DB_CONNECTION=${DB_CONNECTION:-mysql}
DB_HOST=${DB_HOST:-mysql}
DB_PORT=${DB_PORT:-3306}
DB_DATABASE=${DB_DATABASE:-spirit_fruit}
DB_USERNAME=${DB_USERNAME:-spiritfruit}
DB_PASSWORD=${DB_PASSWORD:-spiritfruit_pass}
DB_DEBUG=${DB_DEBUG:-0}

REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}
REDIS_PASSWORD=${REDIS_PASSWORD:-spiritfruit_redis}
REDIS_MAIN_DB=${REDIS_MAIN_DB:-1}
REDIS_CACHE_DB=${REDIS_CACHE_DB:-2}
REDIS_ASYNC_DB=${REDIS_ASYNC_DB:-0}

JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME:-120}
JWT_MAX_REFRESH_TIME=${JWT_MAX_REFRESH_TIME:-86400}

LOG_TYPE=${LOG_TYPE:-single}
LOG_LEVEL=${LOG_LEVEL:-info}
LOG_NAME=${LOG_NAME:-storage/logs/logs.log}

AI_PROVIDER=${AI_PROVIDER:-openai}
OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
OPENAI_IMAGE_MODEL=${OPENAI_IMAGE_MODEL:-dall-e-3}

GETGOAPI_BASE_URL=${GETGOAPI_BASE_URL:-https://api.lingguoai.com/v1}
GETGOAPI_API_KEY=${GETGOAPI_API_KEY:-}
GETGOAPI_MODEL=${GETGOAPI_MODEL:-gpt-4o}
GETGOAPI_IMAGE_MODEL=${GETGOAPI_IMAGE_MODEL:-gpt-4o-image}

DOUBAO_BASE_URL=${DOUBAO_BASE_URL:-https://ark.cn-beijing.volces.com/api/v3}
DOUBAO_API_KEY=${DOUBAO_API_KEY:-}
DOUBAO_MODEL=${DOUBAO_MODEL:-}
DOUBAO_IMAGE_MODEL=${DOUBAO_IMAGE_MODEL:-}

VERTEX_API_KEY=${VERTEX_API_KEY:-}
VERTEX_MODEL=${VERTEX_MODEL:-gemini-1.5-pro}
VERTEX_IMAGE_MODEL=${VERTEX_IMAGE_MODEL:-imagen-3.0-generate-001}
VERTEX_VIDEO_MODEL=${VERTEX_VIDEO_MODEL:-veo-2.0-generate-001}
VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID:-}
VERTEX_REGION=${VERTEX_REGION:-us-central1}
VERTEX_GCS_BUCKET=${VERTEX_GCS_BUCKET:-}

GEMINI_BASE_URL=${GEMINI_BASE_URL:-https://generativelanguage.googleapis.com/v1beta}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
GEMINI_MODEL=${GEMINI_MODEL:-gemini-pro}

VIDEO_PROVIDER=${VIDEO_PROVIDER:-getgoapi}
VOLCES_BASE_URL=${VOLCES_BASE_URL:-https://ark.cn-beijing.volces.com/api/v3}
VOLCES_API_KEY=${VOLCES_API_KEY:-}
MINIMAX_BASE_URL=${MINIMAX_BASE_URL:-https://api.minimax.chat/v1}
MINIMAX_API_KEY=${MINIMAX_API_KEY:-}
RUNWAY_BASE_URL=${RUNWAY_BASE_URL:-https://api.runwayml.com}
RUNWAY_API_KEY=${RUNWAY_API_KEY:-}
PIKA_BASE_URL=${PIKA_BASE_URL:-https://api.pika.art}
PIKA_API_KEY=${PIKA_API_KEY:-}
EOF

exec "$@"
